### ISSUE TITLE
Add repo for Cilium Developer Summits

### ISSUE THREAD

**Issue by lizrice** [cilium/community#173]
### Repository Name

dev-summits

### Type

New

### Repository URL

https://github.com/cilium/dev-summits

### Proposed Scope

Ecosystem

### Motivation for Request

```markdown
We should have a public location for storing notes from Cilium Developer Summits. I think it makes sense to have a separate repo for this, with a folder for each summit (we have now held two, at Paris and SLC 2024).
```

### README

```markdown
https://hackmd.io/@e_RzxKt4QymdRWfhzrzFzQ/HJs3P53MJl
```

### License

Apache 2.0

### Code of Conduct

- [x] I agree to follow Cilium's Code of Conduct

### To be filled by a Cilium committer

- [x] README describes the intent of the repository and has usage examples
- [x] Adheres to one of the [approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md)
- [x] Approved new repository is added into the appropriate list in [REPOSITORIES.md](https://github.com/cilium/community/blob/main/REPOSITORIES.md)

**Comment by xmulligan** [comment]
added to repositories.md with #175
