### ISSUE TITLE
Security Response: Private Distribution List

### ISSUE THREAD

**Issue by xmulligan** [cilium/community#28]
As the project has grown, more vendors are integrating Cilium into their projects and products. It might make sense to have a private distribution list where verified vendors can get early access to security patches to test them out and provide private feedback before they are released.

[Kubernetes](https://github.com/kubernetes/committee-security-response/blob/main/private-distributors-list.md) has a good framework for this and [Envoy](https://github.com/envoyproxy/envoy/blob/main/SECURITY.md#disclosures) and [Istio](https://github.com/istio/community/blob/master/EARLY-DISCLOSURE.md) also follow a similar example.

It is not clear to me yet whether this should be in the community repo, main repo, or a separate new one, but I'm just opening the issue here for now.

**Comment by joestringer** [comment]
Counterpoint, Kees Cook gave a presentation on Linux kernel security response processes at Kernel Recipes 2023 and I think outlines some good reasons *not* to do this at all: https://www.youtube.com/watch?v=2TZe5EROFhE

**Comment by xmulligan** [comment]
It's been about a year since this was first opened without any further progress so I'm going to close this for now, but we can always reopen in the future if there is interest.
