### ISSUE TITLE
Move Governance to the community repo

### ISSUE THREAD

**Issue by xmulligan** [cilium/community#78]
I was talking with @lizrice and we thought it would make more sense to move the governance out of the Cilium docs and into this community repo. 

Governance doesn't quite have "releases" and someone looking at the docs could easily be looking at an outdated version of the governance. Moving it into this repo would decouple governance from the release cycle. Moving it here would also also keep all of the governance docs together since the community ladder and roles already live here. 

https://docs.cilium.io/en/stable/community/governance/commit_access/

**Comment by gailsuccess** [comment]
Hello @xmulligan , I am intrested in working on this prodect during the LFX mentorship. Please I would love to ask for directions on a few queries.

**Lifecycle stage criteria**: What specific criteria will determine the stage of a repo in its lifecycle (e.g., active, experimental, deprecated, archived)?

**Comment by xmulligan** [comment]
Thanks for your interest. I will be working with the mentee and the community to determine that once the project starts

**Comment by MeherRushi** [comment]
Hey @xmulligan and @gailsuccess , I am also interested in contributing to this project. Relatively new here and trying to understand the entire structure but want to try and help.

**Comment by ai-naymul** [comment]
Hi @xmulligan @gailsuccess @MeherRushi ,
Hope you guys doing great. I would love to work on this project as a lfx mentee.

Thank you :)

**Comment by HarshvMahawar** [comment]
@xmulligan Are there any specific needs for the LFX application, such as a proposal or anything else? Thank you.

**Comment by ggold7046** [comment]
Hi @xmulligan, what is the last date for this mentorship application ?

**Comment by octonawish-akcodes** [comment]
https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/01-Mar-May#timeline @ggold7046

**Comment by ggold7046** [comment]
@xmulligan , should I attach the links of my writing sample in a pdf/doc file and upload to the pre-requisite or should I directly upload the pdf file.
``` 
Writing Sample 
Provide a sample of something you've written, school assignments are welcome.
```

**Comment by xmulligan** [comment]
either is fine

**Comment by emirhandogandemir** [comment]
@xmulligan I am really excited to be applying for this and will be providing all the details, hoping I get accepted

**Comment by danyalejaz** [comment]
@xmulligan  I have submitted it today!  I'll be sharing all the necessary details, excited to be a part of this!

**Comment by janvi01** [comment]
Hi @xmulligan I am interested in working on this project under LFX mentorship program.

**Comment by JeeveshGarg** [comment]
Hello @xmulligan , I am intrested in working on this project during the LFX mentorship.

**Comment by Lydia02** [comment]
Hello,

My name is Lydia Ojoawo, and I am currently an undergraduate student specializing in software engineering with a keen interest in technical writing. I have reviewed the requirements for this project associated with the LFX Mentorship Program and have already submitted my application. Additionally, I have joined the relevant Slack channel to stay connected with the community.

I want to inquire if any additional steps or information are required from my end as I eagerly await the approval process. 
Thank you.

**Comment by Nihit25** [comment]
Hey @xmulligan, this issue seems really interesting. I would really like to contribute to this and I'll try my level best to contribute.

**Comment by joestringer** [comment]
> I think a lot of the way we are thinking is similar to how Prometheus currently operates, might be good to borrow some from them when we make the migration

I would strongly recommend that we decouple (a) moving documentation from one place to another from (b) modifying governance documents. The former can be done with minimal oversight to ensure accuracy, whereas the latter requires discussion and approval from Cilium committers.

**Comment by xmulligan** [comment]
Sorry, that's a very good point. Let me create a separate issue for this
