### ISSUE TITLE
Project Charter

### ISSUE THREAD

**Issue by xmulligan** [cilium/community#85]
I was looking through some of the TAG Contributor Strategy documentation and came across the section on [project charters](https://contribute.cncf.io/maintainers/governance/charter/).

"The purpose of having a charter for your open source project is to help people understand the mission, scope, and values / principles, and having this documented early can help avoid issues and misunderstandings later."

This could take the form of Mission, Scope, Values, and/or Principles. May be something for us to consider.

**Comment by lizrice** [comment]
This will be addressed by #101
